### Login de parceiro 
# @name loginPartner1

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partiner1@user.com",
    "password": "secret"
}

### 
@tokenPartner1 = {{ loginPartner1.response.body.token }}

### Login de customer

# @name loginCustomer1

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "customer1@user.com",
    "password": "secret"
}

### 
@tokenCustomer1 = {{ loginCustomer1.response.body.token }}

###
// Criação do partner 
POST http://localhost:3000/partners/register
Content-Type: application/json

{
    "name": "Partner",
    "email": "partiner1@user.com",
    "password": "secret",
    "company_name": "Company Name"
}

###
// Criação de customer
POST http://localhost:3000/customers/register
Content-Type: application/json

{
    "name": "Customer 1",
    "email": "customer1@user.com",
    "password": "secret",
    "address": "addres test",
    "phone": "21 98989898"
}

### Criação de evento pelo parceiro
POST http://localhost:3000/partners/events
Content-Type: application/json
Authorization: Bearer {{ tokenPartner1 }}

{
    "name": "Event teste 1",
    "description": "description test",
    "date": "2025-01-01T00:00:00",
    "location": "location test"
}

### Listagem de eventos do parceiro
GET http://localhost:3000/partners/events
Authorization: Bearer {{ tokenPartner1 }}


### Listagem de um evento do parceiro
GET http://localhost:3000/partners/events/1
Authorization: Bearer {{ tokenPartner1 }}

### Listagem de eventos
GET http://localhost:3000/events


### Listagem de um evento púbico
GET http://localhost:3000/events/1

### Criação de tickets
POST http://localhost:3000/events/1/tickets
Content-Type: application/json
Authorization: Bearer {{ tokenPartner1 }}

{
    "num_tickets": 10,
    "price": 100
}

### Listar tickets de um evento público (Poderia trabalhar com paginação)
GET http://localhost:3000/events/1/tickets

### Listar um ticket específico de um evento
GET http://localhost:3000/events/1/tickets/1

### Compra dos tickets
POST http://localhost:3000/purchases
Content-Type: application/json
Authorization: Bearer {{ tokenCustomer1 }}

{
    "ticket_ids": [1],
    "card_token": "tok_visa"
}

### Rota base
GET http://localhost:3000/
